# Generated by Django 2.0.5 on 2018-05-30 22:32

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('yelpID', models.CharField(max_length=100)),
                ('yelpUrl', models.URLField(unique=True, verbose_name='URL')),
                ('name', models.CharField(max_length=200)),
                ('rating', models.IntegerField(max_length=1)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('location', models.CharField(max_length=300)),
            ],
        ),
    ]
